### ISSUE TITLE
Regarding Source Text of Sentences of Reverb 45

### ISSUE THREAD

**Issue by pashu123** [malllabiisc/cesi#1]
> Firstly, for every triple in ReVerb, we extracted the source text from Clueweb09 corpus from which the triple was generated. In this process, we rejected triples for which we could not find any source text

Can the source text document information be please shared?

**Comment by svjan5** [comment]
The source text sentences of Reverb45k are included in the dataset. They are listed under the "src_sentences" key. Please check.

**Comment by pashu123** [comment]
No, I meant the documents ids/text from where these "src_sentences" came from.

**Comment by svjan5** [comment]
Sorry, that will be a bit hard for me to provide. But you can do that by yourself it is not that difficult.
