### ISSUE TITLE
Error in src/skge/util.py

### ISSUE THREAD

**Issue by ayushgupt** [malllabiisc/cesi#2]
```
def getPairs(id_list, id2clust, mode = 'm2o'):
	pairs = set()
	map_clust = dict()

	for ele in id_list:
		if ele in id2clust: map_clust[ele] = id2clust[ele]

	Z = len(map_clust.keys())

	clusters = invertDic(map_clust, mode)

	for _, v in clusters.items():
		pairs.union(itertools.combinations(v, 2))

	return list(pairs), Z
```

In this code, itertools.combinations(v,2) returns just a itertoolsclass object, so it should be typecast to set, also pair.union didn't update pair inplace and hence that line should be changed to `pairs=pairs.union(set(itertools.combinations(v, 2)))`. I am using python3.

If I rerun with this modification on reverb45k dataset, then pairwise accuracy seems to drop, could you please help?

**Comment by svjan5** [comment]
Hi @ayushgupt,
For the results in the paper, I used python2. These might be required in python3.
