### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by XXWANG-725** [malllabiisc/cesi#3]
Hi, the version of python i used is 3.6, and others are installed by following the requirement. However, throw the value error **ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216**, which means the version of numpy is too low. But when i updated numpy, ran again, it will throw file not found error **FileNotFoundError: [Errno 2] No such file or directory: './output/reverb45_test_run/triples.txt'**, which is reall strange.
Is there any solution to solve it?
Thanks!

**Comment by awxro** [comment]
I upgraded to **numpy==1.16.0** and it finished the setup phase.

**Comment by svjan5** [comment]
Hi @173002612, just do `mkdir output` to resolve the file not found error. This code is a bit old (2017) so numpy version used is of that time only which you need to install to get it working.
