### ISSUE TITLE
error in getPPDBclustersRaw

### ISSUE THREAD

**Issue by gkiril** [malllabiisc/cesi#4]
After running all installation steps, I run the script `python src/cesi_main.py -name reverb45_test_run` . Then, I get the following error:

```
2020-10-02 11:45:51,494 - [INFO] - Running reverb45_test_run
2020-10-02 11:45:51,494 - [INFO] - Reading Triples
2020-10-02 11:45:51,494 - [INFO] -      Loading cached triples
2020-10-02 11:45:52,521 - [INFO] - Side Information Acquisition
Error! Status code :500
Traceback (most recent call last):
  File "src/cesi_main.py", line 234, in <module>
    cesi.get_sideInfo() # Side Information Acquisition
  File "src/cesi_main.py", line 89, in get_sideInfo
    self.side_info = SideInfo(self.p, self.triples_list, self.amb_mentions, self.amb_ent, self.isAcronym)
  File "/home/kgashteovski/cesi/cesi/src/sideInfo.py", line 24, in __init__
    self.fixTypos(amb_ent, amb_mentions, isAcronym)
  File "/home/kgashteovski/cesi/cesi/src/sideInfo.py", line 413, in fixTypos
    ent2ppdb = getPPDBclustersRaw(self.p.ppdb_url, sub_list)
  File "/home/kgashteovski/cesi/cesi/src/helper.py", line 118, in getPPDBclustersRaw
    if rep_list[i] == None: continue        # If no representative for phr then skip
TypeError: 'NoneType' object is not subscriptable
```
Any idea how to fix this quickly?

**Comment by svjan5** [comment]
Hi @gkiril , 
Are you running the PPDB server on another terminal?

**Comment by gkiril** [comment]
Yes, I am

**Comment by svjan5** [comment]
It has been a very long time since I worked on this project so I cannot solve it by looking at this error. Please investigate further on the issue and let me from where the `None` object is coming from.

**Comment by gkiril** [comment]
Hi @svjan5 

Thank you very much for your answer. 

I tracked the issue to `queryPPDB` in `helper.py`. In particular, for line 88:

`req = requests.post(ppdb_url + 'ppdbAll', data=json.dumps(data), headers=headers)`

`req.status_code` is 500, not 200. 

Also, it's worth noting that I am trying to run this code on a GPU server. Is it possible that this is somehow the problem? (e.g., on my laptop running the script works fine when run locally)

Any idea why this is and how to fix it?

**Comment by svjan5** [comment]
Hi @gkiril,
Thanks for looking into the issue. Seems like the issue is with PPDB server only.
The code doesn't make use of any GPUs etc (it uses numpy only) so it should not make much difference. Mostly the PPDB server is not accessible on the server because of some reason (firewall, private network). If it runs locally for you then it is good news it should work with some effort on the server as well.

**Comment by gkiril** [comment]
Is it possible to run CESI without the use of the PPDB server? For instance, to load and query the data in a simpler way (i.e. from files)?

**Comment by svjan5** [comment]
One way is that we can avoid using PPDB side information completely. It should not hurt the performance much. Just comment out the line where PPDB information is getting used then it should work without any problem.

**Comment by gkiril** [comment]
Hi @svjan5 

we solved the issue. The problem in the following line:
`req = requests.post(ppdb_url + 'ppdbAll', data=json.dumps(data), headers=headers)`
was that the servers were binding to localhost, not to `network-ip:9997`. When we hard-coded the address 
`req = requests.post('http://network-ip/ppdbAll', data=json.dumps(data), headers=headers)` 
the problem was gone. 

Thank you very much for your helpful advises on the matter. The issue can be closed.

**Comment by svjan5** [comment]
No problem! Thanks for sharing the solution to the issue.
