### ISSUE TITLE
Process custom data

### ISSUE THREAD

**Issue by gkiril** [malllabiisc/cesi#5]
Suppose I have some dataset (other than Reverb45k) which I formatted previously in the format described on the README page. How can I run CESI to learn the canonicalizations from the other dataset?

**Comment by svjan5** [comment]
I think you just need to change the path to your new data in the code.

**Comment by gkiril** [comment]
Yes, but where exactly? For instance, I see the reverb45k data is located in "data/reverb45k" and there we have two datasets: reverb45k_test and reverb45k_valid (though, I don't see "train"). None of these datasets are specified anywhere in the code (or at least I cannot locate them). 

Suppose I place 3 json files (written in the format described in the README) in "data/new_data" and are named as "new_data_train", "new_data_valid", "new_data_test". Where do we encode this in the code (or give it as input arguments in the command line)?

**Comment by svjan5** [comment]
Hi @gkiril,
Actually, the method does not require training data because there are no parameters. It directly clusters the given knowledge graph. That's why only valid and test are there. 

There is a command-line argument `-data` that you need change

**Comment by gkiril** [comment]
Hi @svjan5, 

thank you very much for your answers, it is clear how CESI works with other data now. In what follows, I will post the explicit solution in case someone else needs it. 

1. Go to folder `data` and open a new folder for your new data (say, `data_new`).
2. In that folder, save the validation and test data with the following file names: `data_new_valid` and `data_new_test`
3. Go to function `cesi_main.py` and locate the following line:
    `parser.add_argument('-data', dest='dataset', default='reverb45k', help='Dataset to run CESI on')`
4. Replace `reverb45k` with `data_new`
5. Run `python src/cesi_main.py -name new_data_test_run`. The results are written in `output/new_data_test_run`

**Comment by svjan5** [comment]
Thank you @gkiril for listing the steps.
