### ISSUE TITLE
Using CESI with large dataset

### ISSUE THREAD

**Issue by gkiril** [malllabiisc/cesi#6]
Suppose we have very large data set with millions of OIE triples. In such scenario, CESI runs out of memory. What are the most memory intensive side information procedures that one can ignore in order to get canonicalized data from a large dataset, while at the same time not damaging precision too much?

**Comment by svjan5** [comment]
I am not 100% sure but mostly token overlap seems to be most expensive based on the implementation. However, there should be some way to optimize it.

**Comment by gkiril** [comment]
Hi @svjan5 ,

thank you very much, this answers my question.
