### ISSUE TITLE
Training, Validation, and Test Splits?

### ISSUE THREAD

**Issue by mlpotter** [malllabiisc/cesi#7]
I read your paper "CESI: Canonicalizing Open Knowledge Bases using Embeddings and Side Information", and I see the following remark for the Reverb45k dataset construction:

"Through these steps, we obtained 45K high-quality triples which we used for evaluation. We call this resulting dataset ReVerb45K." 

I see the 45k triples are shown in the data\reverb45k\reverb45k_valid.txt +  data\reverb45k\reverb45k_test.txt files in this github repo. 

**Can you explain how these two .txt files alone are used to create the automatically learned embeddings from the objective function in section 5, as well as compute the F1 scores in evaluation? Is there no training dataset separate from these two .txt files in your github repo?**

**Comment by svjan5** [comment]
Hi @mlpotter
Thanks for your interest in our work. 
Please note that the CESI model has no parameters to be learned. Therefore, there is no training split in ReVerb45K dataset. For a given graph based on the graph structure and the side information we embed each relation and entity and then perform clustering over it. The .txt files contain the side information and the graph structure information comes from the triples both are together used for learning the embeddings. 

Let me know if you have any other query.

**Comment by mlpotter** [comment]
Hello,

So just to clarify for my sanity.

![image](https://user-images.githubusercontent.com/35242331/101408794-c87d4b80-3891-11eb-8bb0-54cd61cedd94.png)

In this objective function, the learned word embeddings (this is what I consider parameters, in this case an affine transformation) are found by combining the information of both the validation and the test files? 

And also,  to tune the learned embeddings in this objective function, how do you choose the lambdas via grid search?

Thank you so much for replying.

**Comment by svjan5** [comment]
Yes, we can call embeddings as "parameters" of the model. For validation and test, the input graphs are different so sharing is not possible. Yes, lambdas are selected via grid search.
